apiVersion: v1
kind: Namespace
metadata:
  name: colis-dev
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: c3m-integration-test
  namespace: colis-dev
  labels:
    app: c3m-integration-test
spec:
  replicas: 2 #We always want more than 1 replica for HA
  selector:
    matchLabels:
      app: c3m-integration-test
  template:
    metadata:
      labels:
        app: c3m-integration-test
    spec:
      containers:
        - name: c3m-integration-test #1st container
          image: tidusant/c3m-integration-test:latest #Dockerhub image
          ports:
            - containerPort: 8081 #Exposes the port 8901 of the container test
          env:            
            - name: API_URL
              value: "c3m-integration-test-service.colis-dev.svc.cluster.local:30081"            

